### ISSUE TITLE
Incorrect shipping region

### ISSUE THREAD

**Issue by gamesandmore4btc** [duosearch/Duo-Search#1]
Hi there,

A quick question regarding one of my listings which states shipping origin is the United States.

All of my listings are UK based and I currently only ship domestically.

Do you know why it is showing as this? 

Otherwise, I think that the service is fantastic and a strong component of OpenBazaar.

https://duosear.ch/0b0035ebd04f04a4b4f6e7e65e9fcf1059f2757d/listing/e11331ad4c802f79b22433a49f968c19ffb4427a

Thanks,
W

**Comment by duosearch** [comment]
Thanks for submitting an issue! The link provided shows the UK as the shipping origin. Maybe you found how to set it properly in the client?

![screen shot 2016-07-08 at 12 33 17](https://cloud.githubusercontent.com/assets/18505477/16686172/37366962-4508-11e6-9943-6e01ce705c00.png)

**Comment by duosearch** [comment]
BTW cool store. I suggest registering an OpenBazaar handle and adding more contact information.

**Comment by gamesandmore4btc** [comment]
Thank you for the tips, we are looking to get a whole lot more listings online asap. Working on a hosted solution to improve up time. I registered for a handle earlier yesterday, but, am awaiting verification. More contact information is also a good idea, do you think that leaving a phone number is advisable? I've got to get some graphics done and build a facebook/twitter.

Are you able to measure traffic? I know that is a major gripe with the main client from serious vendors. If you could offer that analysis on Duosearch traffic I know vendors would go nuts for that. Currently the only data I can find is general network data and not vendor/store specific.

Also having a way for users to do direct purchases via Duosearch could do lots for consumer adoption. Just like everyone keeps saying for bitcoin to grow "it's got to be easy for consumers to use". Is that a future possibility?

Duosearch > Bazaarbay

Thanks again!

**Comment by duosearch** [comment]
Sounds like you have everything under control; nice!

> Are you able to measure traffic?

Yes, but we've only got Google Analytics setup which gives a rough overview. We've going to be recording pageviews for stores and listings at some point, and we'll probably give away that information publicly.

> Also having a way for users to do direct purchases via Duosearch could do lots for consumer adoption. Is that a future possibility?

Yes, it's a future possibility, and we're planning for it. Doing it properly (regarding security, privacy, usability, scalability, robustness, etc.) is hard, but we're up to the challenge.

**Comment by duosearch** [comment]
> do you think that leaving a phone number is advisable?

There's currently no field specially for phone number. I think leaving a phone number adds value for your customers.

**Comment by gamesandmore4btc** [comment]
Thanks again for the advice. All of my stock and sales is above board so I think I will add a phone number in description (or perhaps under website section).

Any traffic statistics with regard to search terms and page traffic are essential for e-commerce inventory management. On client this seems impossible due to privacy, however, I think users of clearnet portals such as duo are less concerned with privacy and more concerned with ease of use. (Unless they are browsing via tor and those people probably aren't bothered about being included in usage statistics). 

On the above users if clearnet portals using tor or simply wanting ease of use. Supporting direct payment could be a possibility, generating addresses etc. Totally understand it's much more complicated than just that though!

BazaarHound supposedly supports payments via the app, although I haven't tried that myself. 

Thanks for reading my ramblings and hopefully food for thought.

**Comment by gamesandmore4btc** [comment]
Excuse the odd error I'm writing this all on a new phone
