### ISSUE TITLE
Listing is not appearing on Duosearch

### ISSUE THREAD

**Issue by sha-265** [duosearch/Duo-Search#5]
Hi,
I listed some products yasterday, but I can't see this listing on your website.
The listing appears on [bazaarbay.org](https://bazaarbay.org/8d95f535d1b0fca74186dd15433333864f8e0bd8/listing/c6a03148bc1cb65112678b5044f14914fe2bac84).
Is it a bug?

**Comment by JustinDrake** [comment]
Hi Bitim!

Not a bug. Duo Search doesn't display listings with missing images. As you can see on the BazaarBay link, 5 of the images didn't download. This suggests a bad internet connection.

Also, your store has been unreachable for 2 months. (See your store page [here](https://duosear.ch/8d95f535d1b0fca74186dd15433333864f8e0bd8).)

**Comment by sha-265** [comment]
It's not making sense, because I listed this product two days ago. So how bazaarbay.org, can see this listing if I'm offline for two months?

**Comment by JustinDrake** [comment]
Good question. BazaarBay reports seeing your store 20 hours ago. A possible explanation is that your store was online for just a few seconds, and Duo Search didn't get an opportunity to scrape your profile. It's hard to tell was exactly happened.

My suggestion for hosting a reliable store is to use www.deploy.ob1.io. If you want to host from a home connection, avoid hosting from a Raspberry Pi.

**Comment by sha-265** [comment]
The client is still running. And it's not hosted on Raspberry Pi. Maybe I should open some port for it?

**Comment by JustinDrake** [comment]
I can just about connect to your store with the reference client. Could you try rebooting your client? What version of the client are you using?

**Comment by sha-265** [comment]
I did restart the client multiple times today. Using version 1.1.10.
